### ISSUE TITLE
a typo in how-2-test-cc-non-vagrant.md

### ISSUE THREAD

**Issue by rupc** [asararatnakar/fabric_v1_Chaincode_instructions#1]
Hi! I found a typo in https://github.com/asararatnakar/fabric_v1_Chaincode_instructions/blob/master/how-2-test-cc-non-vagrant.md#terminal-window-tab-2-1

After executing 
```bash
"CORE_PEER_FILESYSTEMPATH=hyperledger/production ./build/bin/peer node start -o 127.0.0.1:7050"
```
That terminal does not open stdin/stdout. I think third terminal window is needed.

Thanks

**Comment by asararatnakar** [comment]
@rupc Yes you are right, Its a typo and must be Third window . Thanks for pointing it out. I corrected it now.
